[package]
name = "ubootflashdumper"
version = "0.1.0"
authors = ["nikos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4.0"
clap = "2.33.3"